"""R2-first prospective deep-data observatory."""

from robin.prospective_observatory.budgets import (
    API_FOOTBALL_PROVIDER_RESERVE,
    MAX_API_FOOTBALL_CALLS_TOTAL,
    MAX_ODDS_API_CREDITS_TOTAL,
    ODDS_API_PROVIDER_RESERVE,
    ODDS_NEAR_KICKOFF_RESERVE,
    BudgetExceeded,
    BudgetLedger,
    BudgetPolicy,
    CircuitBreaker,
    ProviderKind,
)
from robin.prospective_observatory.contracts import (
    AvailabilityStatus,
    CaptureAttempt,
    CaptureContext,
    CaptureFamily,
    CaptureReceipt,
    CaptureWindow,
    ProspectiveFixture,
)
from robin.prospective_observatory.gates import (
    GateEvaluation,
    GateName,
    GateObservation,
    GateStatus,
    aggregate_gate_evaluations,
    evaluate_fixture_gates,
)
from robin.prospective_observatory.hypotheses import (
    FrozenProspectiveProtocol,
    HypothesisProgress,
    frozen_h11_protocols,
    hypothesis_progress,
)
from robin.prospective_observatory.ledger import (
    EvidenceEventKindV3,
    PublicEvidenceLedgerV3,
    build_observatory_ledger,
    observatory_ledger_summary,
)
from robin.prospective_observatory.r2 import (
    AppendOnlyViolation,
    InMemoryObjectStore,
    ObjectStore,
    ProspectiveR2Repository,
    StoredCapture,
    deterministic_r2_keys,
)
from robin.prospective_observatory.replay import (
    InMemoryProjectionSink,
    ProjectionSink,
    ReplayResult,
    replay_from_r2,
)
from robin.prospective_observatory.temporal import (
    CAPTURE_POLICIES,
    classify_window,
    retry_disposition,
    schedule_windows,
    temporal_admissibility,
)

__all__ = [
    "API_FOOTBALL_PROVIDER_RESERVE",
    "CAPTURE_POLICIES",
    "MAX_API_FOOTBALL_CALLS_TOTAL",
    "MAX_ODDS_API_CREDITS_TOTAL",
    "ODDS_API_PROVIDER_RESERVE",
    "ODDS_NEAR_KICKOFF_RESERVE",
    "AppendOnlyViolation",
    "AvailabilityStatus",
    "BudgetExceeded",
    "BudgetLedger",
    "BudgetPolicy",
    "CaptureAttempt",
    "CaptureContext",
    "CaptureFamily",
    "CaptureReceipt",
    "CaptureWindow",
    "CircuitBreaker",
    "EvidenceEventKindV3",
    "FrozenProspectiveProtocol",
    "GateEvaluation",
    "GateName",
    "GateObservation",
    "GateStatus",
    "HypothesisProgress",
    "InMemoryObjectStore",
    "InMemoryProjectionSink",
    "ObjectStore",
    "ProjectionSink",
    "ProspectiveFixture",
    "ProspectiveR2Repository",
    "ProviderKind",
    "PublicEvidenceLedgerV3",
    "ReplayResult",
    "StoredCapture",
    "aggregate_gate_evaluations",
    "build_observatory_ledger",
    "classify_window",
    "deterministic_r2_keys",
    "evaluate_fixture_gates",
    "frozen_h11_protocols",
    "hypothesis_progress",
    "observatory_ledger_summary",
    "replay_from_r2",
    "retry_disposition",
    "schedule_windows",
    "temporal_admissibility",
]
