"""Receipt-backed, offline-first market capture harness."""

from robin.capture.contracts import (
    CaptureBudget,
    CaptureContractError,
    CaptureManifest,
    CaptureMode,
    FixtureMapping,
    InternalRetentionPolicy,
    NormalizedMarketObservation,
    OfflineReplayResult,
    ProviderRequestSpec,
    QuotaObservation,
    RawPayloadReceipt,
    RequestFingerprint,
    SchemaFingerprint,
)
from robin.capture.harness import (
    LIVE_CANARY_AUTHORIZED,
    CaptureGuardError,
    CaptureHarness,
    CaptureRejected,
    SecretCapability,
)
from robin.capture.live_contracts import (
    LIVE_ALLOWED_MARKET_SETS,
    LIVE_ALLOWED_MARKETS,
    LIVE_ALLOWED_REGION,
    LIVE_ALLOWED_SPORT_KEYS,
    LIVE_CAPABILITY_VERSION,
    LIVE_MISSION_ID,
    ActivationEnvelopeV1,
    LiveAdmissionPermitV1,
    LiveCaptureLineageV1,
    LiveExecutionAttemptReceiptV1,
    LiveExecutionReceiptV1,
    LiveLeaseV1,
    LivePlanItemV1,
    LivePlanV1,
    LiveResponseIntakeClaimV1,
    LiveTerminalDisposition,
    OwnerAuthorizationV1,
)
from robin.capture.live_executor import (
    BoundedLiveCanaryExecutor,
    GitRepositoryStateReader,
    LiveGuardError,
    OwnerAuthorizationVerifier,
    PinnedOwnerAuthorizationVerifier,
    RepositoryStateV1,
    fixture_mappings_sha256,
)
from robin.capture.live_storage import LiveBudgetReservation, LiveStateStore, LiveStorageError
from robin.capture.live_transport import (
    EnvironmentSecretReader,
    LiveTransportError,
    LiveTransportResponse,
    PublicProviderRequestV1,
    StrictHttpsTransport,
)
from robin.capture.storage import CaptureStore

__all__ = [
    "LIVE_CANARY_AUTHORIZED",
    "LIVE_ALLOWED_MARKET_SETS",
    "LIVE_ALLOWED_MARKETS",
    "LIVE_ALLOWED_REGION",
    "LIVE_ALLOWED_SPORT_KEYS",
    "LIVE_CAPABILITY_VERSION",
    "LIVE_MISSION_ID",
    "ActivationEnvelopeV1",
    "BoundedLiveCanaryExecutor",
    "CaptureBudget",
    "CaptureContractError",
    "CaptureGuardError",
    "CaptureHarness",
    "CaptureManifest",
    "CaptureMode",
    "CaptureRejected",
    "CaptureStore",
    "FixtureMapping",
    "GitRepositoryStateReader",
    "InternalRetentionPolicy",
    "LiveBudgetReservation",
    "LiveAdmissionPermitV1",
    "LiveCaptureLineageV1",
    "LiveExecutionAttemptReceiptV1",
    "LiveExecutionReceiptV1",
    "LiveGuardError",
    "LiveLeaseV1",
    "LivePlanItemV1",
    "LivePlanV1",
    "LiveResponseIntakeClaimV1",
    "LiveStateStore",
    "LiveStorageError",
    "LiveTerminalDisposition",
    "LiveTransportError",
    "LiveTransportResponse",
    "NormalizedMarketObservation",
    "OfflineReplayResult",
    "OwnerAuthorizationV1",
    "OwnerAuthorizationVerifier",
    "PinnedOwnerAuthorizationVerifier",
    "ProviderRequestSpec",
    "QuotaObservation",
    "RawPayloadReceipt",
    "RequestFingerprint",
    "RepositoryStateV1",
    "SchemaFingerprint",
    "SecretCapability",
    "EnvironmentSecretReader",
    "PublicProviderRequestV1",
    "StrictHttpsTransport",
    "fixture_mappings_sha256",
]
