"""Historical Deep Data Harvest V1 core primitives."""

from robin.historical_deep.contracts import (
    CampaignContract,
    CompetitionSpec,
    DataFamily,
    DatasetName,
    GateStatus,
    HarvestTask,
    HarvestVerdict,
    ProviderStatus,
    QuotaBudget,
    TaskStatus,
    TemporalClass,
    build_task_id,
    load_campaign_contract,
)
from robin.historical_deep.provider import (
    ApiFootballDeepClient,
    CircuitOpenError,
    ProviderError,
    ProviderRateLimitError,
    ProviderResponse,
    ProviderResponseError,
    ProviderStatusError,
    ProviderTransportError,
)
from robin.historical_deep.quota import (
    QuotaController,
    QuotaExhaustedError,
    QuotaStatusExpiredError,
)
from robin.historical_deep.storage import (
    AppendOnlyViolation,
    HarvestCheckpoint,
    HarvestReceipt,
    InMemoryObjectStore,
    ObjectStore,
    PayloadIntegrityError,
    R2FirstRepository,
    StoredPayload,
    TaskAttemptEvent,
)

__all__ = [
    "ApiFootballDeepClient",
    "AppendOnlyViolation",
    "CampaignContract",
    "CircuitOpenError",
    "CompetitionSpec",
    "DataFamily",
    "DatasetName",
    "GateStatus",
    "HarvestCheckpoint",
    "HarvestReceipt",
    "HarvestTask",
    "HarvestVerdict",
    "InMemoryObjectStore",
    "ObjectStore",
    "PayloadIntegrityError",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderResponse",
    "ProviderResponseError",
    "ProviderStatus",
    "ProviderStatusError",
    "ProviderTransportError",
    "QuotaBudget",
    "QuotaController",
    "QuotaExhaustedError",
    "QuotaStatusExpiredError",
    "R2FirstRepository",
    "StoredPayload",
    "TaskAttemptEvent",
    "TaskStatus",
    "TemporalClass",
    "build_task_id",
    "load_campaign_contract",
]
