"""Interfaces communes des fournisseurs football et cotes."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Protocol


class FootballProvider(Protocol):
    def get_competitions(self) -> Sequence[Mapping[str, object]]: ...

    def get_seasons(self) -> Sequence[Mapping[str, object]]: ...

    def get_teams(self) -> Sequence[Mapping[str, object]]: ...

    def get_players(self) -> Sequence[Mapping[str, object]]: ...

    def get_fixtures(self) -> Sequence[Mapping[str, object]]: ...

    def get_lineups(self) -> Sequence[Mapping[str, object]]: ...

    def get_events(self) -> Sequence[Mapping[str, object]]: ...

    def get_team_statistics(self) -> Sequence[Mapping[str, object]]: ...

    def get_player_statistics(self) -> Sequence[Mapping[str, object]]: ...

    def get_injuries(self) -> Sequence[Mapping[str, object]]: ...

    def get_suspensions(self) -> Sequence[Mapping[str, object]]: ...

    def get_odds(self) -> Sequence[Mapping[str, object]]: ...


class PayloadBackend(Protocol):
    def put_if_absent(self, object_key: str, payload: bytes) -> str: ...

    def read(self, object_key: str) -> bytes: ...

