"""Interfaces communes des fournisseurs football et cotes."""

from __future__ import annotations

from typing import Protocol

from robin.providers.contracts import ProviderResult


class FootballProvider(Protocol):
    def get_competitions(self) -> ProviderResult: ...

    def get_seasons(self) -> ProviderResult: ...

    def get_teams(self) -> ProviderResult: ...

    def get_players(self) -> ProviderResult: ...

    def get_fixtures(self) -> ProviderResult: ...

    def get_results(self) -> ProviderResult: ...

    def get_lineups(self) -> ProviderResult: ...

    def get_events(self) -> ProviderResult: ...

    def get_team_statistics(self) -> ProviderResult: ...

    def get_player_statistics(self) -> ProviderResult: ...

    def get_injuries(self) -> ProviderResult: ...

    def get_suspensions(self) -> ProviderResult: ...

    def get_odds(self) -> ProviderResult: ...


class PayloadBackend(Protocol):
    def put_if_absent(self, object_key: str, payload: bytes) -> str: ...

    def read(self, object_key: str) -> bytes: ...
