"""VAGUE 1 — hypotheses PRE-ENREGISTREES (Session 2, registre v1).
Ne pas modifier apres le debut d'un backtest (delta 5 : pre-enregistrement).
cond : conditions ANDees par scope ; any_* : au moins une vraie.
"""

VAGUE1 = [
    # ---- mono-atomes Tier A (mapping registre) ----
    dict(id="S002", nom="Serie longue de victoires", cond=dict(self_=["SERIE_V_LONGUE"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S005", nom="Objectif clair + forme", cond=dict(self_=["SERIE_VICTOIRES"], any_self=[["LUTTE_TITRE", "LUTTE_MONTEE", "LUTTE_MAINTIEN"]]), marches=["WIN_SELF", "TEAM_O15_SELF"]),
    dict(id="S006", nom="Serie negative importante", cond=dict(self_=["SERIE_SANS_V"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="S022", nom="Derby chaud -> cartons", cond=dict(match=["DERBY_CHAUD"]), marches=["O45_CARTONS"]),
    dict(id="S023", nom="Derby + H2H under", cond=dict(match=["DERBY", "H2H_UNDER25"]), marches=["U25"]),
    dict(id="S024", nom="Revanche de derby", cond=dict(self_=["H2H_REVANCHE", "SERIE_VICTOIRES"], match=["DERBY"]), marches=["WIN_SELF"]),
    dict(id="S033", nom="Domination locale H2H", cond=dict(self_=["H2H_DOMINATION_LOCALE", "VENUE_DOM"]), marches=["WIN_SELF", "DC_SELF"]),
    # S035/S036 (post-Europe) : NON EVALUABLES v1 — necessitent le calendrier UEFA (v1.1)
    dict(id="S037", nom="Recuperation courte", cond=dict(self_=["REPOS_COURT"]), marches=["WIN_ADV", "TEAM_U15_SELF"]),
    dict(id="S038", nom="Recuperation longue", cond=dict(self_=["REPOS_LONG"]), marches=["WIN_SELF", "CS_SELF"]),
    dict(id="S044", nom="Apres defaite lourde", cond=dict(self_=["POST_DEFAITE_LOURDE"]), marches=["WIN_ADV"]),
    dict(id="S045", nom="Humiliation en derby", cond=dict(self_=["POST_DEFAITE_LOURDE"], match=["DERBY"]), marches=["WIN_ADV", "TEAM_O15_ADV"]),
    dict(id="S049", nom="Fort en MT1", cond=dict(self_=["FORT_MT1"]), marches=["MT1_SELF", "O05_MT1"]),
    dict(id="S050", nom="Encaisse en MT1", cond=dict(self_=["ENCAISSE_MT1"]), marches=["O05_MT1", "MT1_ADV"]),
    dict(id="S051", nom="Solide en MT1", cond=dict(self_=["SOLIDE_MT1"]), marches=["U05_MT1"]),
    dict(id="S052", nom="Fort en MT2", cond=dict(self_=["FORT_MT2"]), marches=["MT2_SELF"]),
    dict(id="S054", nom="Forteresse", cond=dict(self_=["FORTERESSE"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S056", nom="Solide dans les chocs", cond=dict(self_=["FIN_SAISON_FORTE_HISTO"], match=["MATCH_A_ENJEU"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S057", nom="Faible a domicile", cond=dict(self_=["FAIBLE_DOMICILE"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="S058", nom="Voyageur fort", cond=dict(self_=["VOYAGEUR_FORT"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S059", nom="Faible a l'exterieur", cond=dict(self_=["FAIBLE_EXTERIEUR"]), marches=["WIN_ADV", "CS_ADV"]),
    dict(id="S060", nom="Finisseur de saison", cond=dict(self_=["FIN_SAISON_FORTE_HISTO"], match=["FENETRE_FIN_SAISON"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S061", nom="Defense passoire", cond=dict(self_=["DEFENSE_PASSOIRE"]), marches=["TEAM_O15_ADV", "BTTS_Y", "WIN_ADV"]),
    dict(id="S065", nom="Montee assuree, dynamique", cond=dict(self_=["MONTEE_ASSUREE"]), marches=["WIN_SELF"]),
    dict(id="S066", nom="Objectif rate recent", cond=dict(self_=["OBJECTIF_RATE_RECENT"]), marches=["WIN_ADV"]),
    dict(id="S067", nom="Sans enjeu vs en lutte", cond=dict(self_=["SANS_ENJEU"], any_adv=[["LUTTE_MAINTIEN", "LUTTE_MONTEE", "LUTTE_TITRE"]]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="S068", nom="Serie de nuls", cond=dict(self_=["SERIE_NULS"]), marches=["WIN_ADV"]),
    dict(id="S069", nom="Victoires serrees en serie", cond=dict(self_=["SERIE_V_SERREES"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S070", nom="H2H BTTS", cond=dict(match=["H2H_BTTS"]), marches=["BTTS_Y"]),
    dict(id="S071", nom="H2H Under", cond=dict(match=["H2H_UNDER25"]), marches=["U25"]),
    dict(id="S073", nom="Scoring fou", cond=dict(self_=["SCORING_FOU"]), marches=["O35", "O25"]),
    dict(id="S074", nom="Matchs fermes", cond=dict(self_=["U15_FREQ"]), marches=["U15", "U25"]),
    dict(id="S075", nom="MT1 prolifiques", cond=dict(self_=["O15_MT1_FREQ"]), marches=["O15_MT1"]),
    dict(id="S076", nom="MT1 fermees", cond=dict(self_=["U05_MT1_FREQ"]), marches=["U05_MT1"]),
    dict(id="S077", nom="Course au titre/montee", cond=dict(self_=["SERIE_VICTOIRES"], any_self=[["LUTTE_TITRE", "LUTTE_MONTEE"]]), marches=["WIN_SELF"]),
    dict(id="S078", nom="Survie en forme", cond=dict(self_=["LUTTE_MAINTIEN", "SERIE_VICTOIRES"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S079", nom="Relegue demobilise (duel S081)", cond=dict(self_=["RELEGUE_MATH"]), marches=["WIN_ADV"]),
    dict(id="S080", nom="Maintien assure recent", cond=dict(self_=["MAINTIEN_ASSURE_RECENT"]), marches=["WIN_ADV"]),
    dict(id="S081", nom="Relegue libere (duel S079)", cond=dict(self_=["RELEGUE_MATH", "REPRISE_FORME"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S082", nom="Reprise de forme", cond=dict(self_=["REPRISE_FORME"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S083", nom="Faible contre le haut", cond=dict(self_=["FAIBLE_VS_TOP"], match_opp_top=True), marches=["WIN_ADV", "TEAM_U15_SELF"]),
    dict(id="S089", nom="Domine les faibles", cond=dict(self_=["DOMINE_FAIBLES"], match_opp_bas=True), marches=["WIN_SELF", "TEAM_O15_SELF"]),
    dict(id="S091", nom="Apres victoire large", cond=dict(self_=["POST_VICTOIRE_LARGE"]), marches=["WIN_SELF", "DC_SELF"]),
    # ---- atomes xG (actives seulement si xg.parquet present) ----
    dict(id="S011", nom="Surperformance xG", cond=dict(self_=["XG_SURPERF"]), marches=["WIN_SELF"], xg=True),
    dict(id="S012", nom="Sous-performance xG", cond=dict(self_=["XG_SOUSPERF"]), marches=["WIN_ADV", "TEAM_U15_SELF"], xg=True),
    dict(id="S013", nom="Forte diff xG/xGA", cond=dict(self_=["XG_DIFF_POS"]), marches=["WIN_SELF", "CS_SELF"], xg=True),
    dict(id="S014", nom="Diff xG/xGA negative", cond=dict(self_=["XG_DIFF_NEG"]), marches=["WIN_ADV", "TEAM_O15_ADV"], xg=True),
    dict(id="S015", nom="xG eleve, finition froide", cond=dict(self_=["XG_ELEVE", "RATIO_FINITION_BAS"]), marches=["WIN_SELF", "TEAM_O15_SELF", "BTTS_Y"], xg=True),
    dict(id="S016", nom="Fade la surchauffe", cond=dict(self_=["XG_FAIBLE", "RATIO_FINITION_HAUT"]), marches=["WIN_ADV", "TEAM_U15_SELF"], xg=True),
    dict(id="S017", nom="xG en hausse", cond=dict(self_=["XG_TREND_UP"]), marches=["WIN_SELF", "TEAM_O15_SELF"], xg=True),
    dict(id="S018", nom="xG en chute + xGA en hausse", cond=dict(self_=["XG_TREND_DOWN", "XGA_TREND_UP"]), marches=["WIN_ADV"], xg=True),
    dict(id="S019", nom="Verrou qui se ferme", cond=dict(self_=["XGA_TREND_DOWN"]), marches=["CS_SELF", "TEAM_U15_ADV"], xg=True),
    dict(id="S021", nom="Apres victoire surprise", cond=dict(self_=["POST_VICTOIRE_SURPRISE", "SERIE_VICTOIRES"]), marches=["WIN_SELF", "DC_SELF"]),
    dict(id="S025", nom="Fragilite croissante", cond=dict(self_=["XGA_TREND_UP"]), marches=["TEAM_O15_ADV", "WIN_ADV"], xg=True),
    dict(id="S026", nom="xG eleve et stable", cond=dict(self_=["XG_ELEVE_STABLE"]), marches=["WIN_SELF", "TEAM_O15_SELF"], xg=True),
    dict(id="S063", nom="Libere sans enjeu, xG haut", cond=dict(self_=["SANS_ENJEU", "XG_ELEVE"]), marches=["O25", "TEAM_O15_SELF", "BTTS_Y"], xg=True),
    dict(id="S064", nom="Sans enjeu, defense qui lache", cond=dict(self_=["SANS_ENJEU", "XGA_TREND_UP"]), marches=["WIN_ADV", "TEAM_O15_ADV"], xg=True),
    # ---- composees P1 (Session 2) ----
    dict(id="HC-01", nom="Fatigue asymetrique", cond=dict(self_=["REPOS_COURT"], adv=["REPOS_LONG"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="HC-03", nom="Enjeu asymetrique", cond=dict(self_=["SANS_ENJEU"], any_adv=[["LUTTE_MAINTIEN", "LUTTE_MONTEE", "LUTTE_TITRE"]], match=["FENETRE_FIN_SAISON"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="HC-04", nom="Forteresse vs voyageur malade", cond=dict(self_=["FORTERESSE"], adv=["FAIBLE_EXTERIEUR"]), marches=["WIN_SELF", "CS_SELF"]),
    dict(id="HC-05", nom="Regression croisee", cond=dict(self_=["RATIO_FINITION_HAUT", "XG_FAIBLE"], adv=["XG_TREND_UP"]), marches=["WIN_ADV", "DC_ADV"], xg=True),
    dict(id="HC-06", nom="Duel de passoires", cond=dict(self_=["DEFENSE_PASSOIRE"], adv=["DEFENSE_PASSOIRE"]), marches=["O25", "BTTS_Y", "O35"]),
    dict(id="HC-07", nom="Duel de verrous", cond=dict(self_=["XGA_TREND_DOWN"], adv=["CRISE_OFFENSIVE"]), marches=["U25", "CS_SELF"], xg=True),
    dict(id="HC-08", nom="MT1 croisee", cond=dict(self_=["ENCAISSE_MT1"], adv=["FORT_MT1"]), marches=["O05_MT1", "MT1_ADV", "O15_MT1"]),
    dict(id="HC-10", nom="Derby sous sifflet severe", cond=dict(match=["DERBY_CHAUD", "ARBITRE_SEVERE"]), marches=["O45_CARTONS"]),
    dict(id="HC-11", nom="Frustration vs momentum", cond=dict(self_=["SERIE_NULS"], adv=["SERIE_VICTOIRES"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="HC-12", nom="Lendemain de fete", cond=dict(self_=["POST_VICTOIRE_SURPRISE", "VENUE_EXT"]), marches=["WIN_ADV", "DC_ADV"]),
    dict(id="HC-13", nom="Gala bilateral", cond=dict(self_=["SANS_ENJEU"], adv=["SANS_ENJEU"], match=["FENETRE_FIN_SAISON"]), marches=["O25", "BTTS_Y"]),
]
